engenharia/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from rest_framework.documentation import include_docs_urls
from django.contrib.auth import urls



urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/docs/', include_docs_urls(title='SGO - Documentação da API', public=False)),
    path('', include('sistema.urls', namespace='sistema')),
    path('contas/', include('django.contrib.auth.urls')),

]

if settings.DEBUG is True:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


sistema/api/urls.py
from django.urls import path, include
from rest_framework import routers

from sistema.api import viewset
from rest_framework.authtoken.views import obtain_auth_token
#Swagger



router = routers.DefaultRouter()


router.register(r'usuario', viewset.UsuarioViewApi, base_name='Usuarios')
router.register(r'empresa', viewset.EmpresaListViewAPI, base_name='Empresa')
router.register(r'listarempreendimentos', viewset.EmpreendimentoListViewAPI, base_name='Empreendimento')
router.register(r'listarblocos', viewset.BlocoListViewAPI, base_name='Bloco')
router.register(r'listarapartamentos', viewset.ApartamentoListViewAPI, base_name='Apartamento')
router.register(r'listageralapartamentos', viewset.ApartamentoListaGeral, base_name='Apartamento')
router.register(r'listarcategoriasdeproblema', viewset.CategoriaDeProblemaListViewAPI, base_name='CategoriaDeProblema')
router.register(r'listarareascomuns', viewset.AreaComumListViewAPI, base_name='AreaComum')
router.register(r'imagem', viewset.ImagemUploadViewAPI, base_name='ImagemUpload')
router.register(r'chamado', viewset.ChamadoCreateViewAPI, base_name='Chamado')
router.register(r'listarchamados', viewset.ChamadoListViewAPI, base_name='Chamado')

urlpatterns = [

    path('api/', include(router.urls)),
    path('obter-token/', obtain_auth_token, name='api_token_auth'),


]

sistema/urls.py
# coding=utf-8


from django.urls import path, include
from . import views
from rest_framework.urlpatterns import format_suffix_patterns
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required  #Staff
from django.urls import reverse_lazy
from sistema.api import viewset

app_name = 'sistema'






urlpatterns = [
    path('', include('sistema.api.urls')),

    path('', staff_member_required(views.DashboardView.as_view(), login_url=reverse_lazy('sistema:login')), name='dashboard'),

    #Login e logout
    path('login/', auth_views.login, {'template_name': 'sistema/login.html'}, name='login'),
    path('logout/', auth_views.logout, {'next_page': reverse_lazy('sistema:dashboard')}, name='logout'),


    path('empresa/cadastrarempresa/', staff_member_required(
        views.EmpresaCreateView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='cadastrarempresa'),

    path('empresa/editarempresa/<int:pk>/', staff_member_required(
        views.EmpresaEditView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='editarempresa'),

    path('empresa/deletarempresa/<int:pk>/', staff_member_required(
        views.EmpresaDeleteView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='deletarempresa'),

    path('usuarios/editarusuario/<int:pk>/mudarsenha', staff_member_required(
        views.UsuariosPasswordUpdateView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='mudarsenhausuario'),

    path('usuarios/cadastrarusuario/', staff_member_required(
        views.UsuariosCreateView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='cadastrarusuario'),

    path('usuarios/listarusuarios/', staff_member_required(
        views.UsuariosListView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='listarusuarios'),

    path('usuarios/editarusuario/<int:pk>/', staff_member_required(
        views.UsuariosUpdateView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='editarusuario'),

    path('usuarios/deletarusuario/<int:pk>/', staff_member_required(
        views.UsuariosDeleteView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='deletarusuario'),



    path('empreendimentos/listarempreendimentos/', staff_member_required(
        views.EmpreendimentoListView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='listarempreendimentos'),
    path('empreendimentos/cadastrarempreendimento/', staff_member_required(
        views.EmpreendimentoCreateView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='cadastrarempreendimento'),
    path('empreendimentos/editarempreendimento/<int:pk>/', staff_member_required(
        views.EmpreendimentoUpdateView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='editarempreendimento'),
    path('empreendimentos/deletarempreendimento/<int:pk>/', staff_member_required(
        views.EmpreendimentoDeleteView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='deletarempreendimento'),


    path('empreendimentos/areascomuns/', staff_member_required(
        views.AreasComunsListView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='listarareascomuns'),
    path('empreendimentos/areascomuns/cadastrarareacomum', staff_member_required(
        views.AreaComumCreateView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='cadastrarareacomum'),
    path('empreendimentos/areascomuns/editarareacomum/<int:pk>/', staff_member_required(
        views.AreaComumUpdateView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='editarareacomum'),
    path('empreendimentos/areascomuns/deletarareacomum/<int:pk>/', staff_member_required(
        views.AreaComumDeleteView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='deletarareacomum'),


    path('empreendimentos/blocos/listarblocos/', staff_member_required(
        views.BlocoListView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='listarblocos'),
    path('empreendimentos/blocos/cadastrarbloco/', staff_member_required(
        views.BlocoCreateView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='cadastrarbloco'),
    path('empreendimentos/blocos/editarbloco/<int:pk>/', staff_member_required(
        views.BlocoUpdateView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='editarbloco'),
    path('empreendimentos/blocos/deletarbloco/<int:pk>/', staff_member_required(
        views.BlocoDeleteView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='deletarbloco'),


    path('empreendimentos/blocos/listarapartamentos/', staff_member_required(
        views.ApartamentoListView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='listarapartamentos'),
    path('empreendimentos/blocos/cadastrarapartamento/', staff_member_required(
        views.ApartamentoCreateView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='cadastrarapartamento'),
    path('empreendimentos/blocos/editarapartamento/<int:pk>/', staff_member_required(
        views.ApartamentoUpdateView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='editarapartamento'),
    path('empreendimentos/blocos/deletarapartamento/<int:pk>/', staff_member_required(
        views.ApartamentoDeleteView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='deletarapartamento'),
    path('json/apartamentos/proprietario/<int:pk>', staff_member_required(
         views.ApartamentoProprietarioListJson.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='apartamentoproprietario'),


    path('problemas/listarcategorias/', staff_member_required(
        views.CategoriaDeProblemaListView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='categoriasdeproblemas'),
    path('problemas/cadastrarcategoria/', staff_member_required(
        views.CategoriaDeProblemaCreateView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='cadastrarcategoriadeproblema'),
    path('problemas/editarcategoria/<int:pk>/', staff_member_required(
        views.CategoriaDeProblemaUpdateView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='editarcategoriadeproblema'),
    path('problemas/deletarcategoria/<int:pk>/', staff_member_required(
        views.CategoriaDeProblemaDeleteView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='deletarcategoriadeproblema'),


    path('chamados/listarchamados/', staff_member_required(
        views.ChamadoListView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='listarchamados'),
    path('chamados/cadastrarchamado/', staff_member_required(
        views.ChamadoCreateView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='cadastrarchamado'),
    path('chamados/editarchamado/<int:pk>/', staff_member_required(
        views.ChamadoUpdateView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='editarchamado'),
    path('chamados/deletarchamado/<int:pk>/', staff_member_required(
        views.ChamadoDeleteView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='deletarchamado'),

    path('chamados/imprimir/<int:pk>/', staff_member_required(
        views.ChamadoPrintView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='imprimirchamado'),


    path('chamados/deletarevento/<int:pk>/', staff_member_required(
        views.EventoChamadoDeleteView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='deletareventochamado'),


    path('filtro/chamado/', staff_member_required(
        views.RelatorioChamadoFiltro.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='filtrochamado'),



]

sistema/forms.py
# coding=utf-8
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm
from django import forms
from .models import *
from django.core.exceptions import ValidationError
class EmpresaForm(forms.ModelForm):
    class Meta:
        model = Empresa
        fields = '__all__'


class UsuarioForm(UserCreationForm):
    class Meta:
        model = Usuarios
        #fields = '__all__'
        exclude = ['password', 'last_login', 'is_active', 'date_joined']


class UsuarioEditForm(forms.ModelForm):
    class Meta:
        model = Usuarios
        exclude = ['password', 'last_login', 'is_active', 'date_joined', 'apartamentos']


class UsuarioPasswordChangeForm(UserCreationForm):
    class Meta:
        model = Usuarios
        fields = ['password1', 'password2']


class EmpreendimentoForm(forms.ModelForm):
    class Meta:
        model = Empreendimento
        fields = ['nomeEmpreendimento']


class AreaComumForm(forms.ModelForm):
    class Meta:
        model = AreaComum
        fields = ['nomeArea', ]


class BlocoForm(forms.ModelForm):
    class Meta:
        model = Bloco
        fields = ['empreendimento', 'bloco']


class ApartamentoForm(forms.ModelForm):
    class Meta:
        model = Apartamento
        fields = ['bloco', 'apartamento', 'proprietario', 'inicioGarantia']

    def clean_inicioGarantia(self):
        cleaned_data = super(ApartamentoForm, self).clean()
        inicioGarantia = cleaned_data.get("inicioGarantia")
        proprietario = cleaned_data.get("proprietario")

        if(inicioGarantia == None) and (not (proprietario == None)):
            raise ValidationError("Selecione a data de início da garantia do apartamento.")
        return inicioGarantia

class CategoriaDeProblemaForm(forms.ModelForm):
    class Meta:
        model = CategoriaDeProblema
        fields = ['nomeCategoria']


class ChamadoForm(forms.ModelForm):
    class Meta:
        model = Chamado
        fields = '__all__'
        exclude = ['protocolo', 'novosEventos']



class EventoChamadoForm(forms.ModelForm):
    class Meta:
        model = EventosChamado
        fields = ['descricaoEvento']
        #exclude = ['protocolo']













sistema/templates/sistema/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">

<html>

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <title>{% block title %}Administração{% endblock %}</title>
    <!-- Favicon-->
     <link rel="shortcut icon" type="image/ico" href="{% static 'favicon.ico' %}"/>

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,cyrillic-ext" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">

    <!-- Bootstrap Core Css -->
    <link href="{% static 'plugins/bootstrap/css/bootstrap.css' %}" rel="stylesheet">

    <!-- Waves Effect Css -->
    <link href="{% static 'plugins/node-waves/waves.css' %}" rel="stylesheet" />

    <!-- sweet alert -->
    <link href="{% static 'plugins/sweetalert/sweetalert.css' %}" rel="stylesheet" />

    <!-- Animation Css -->
    <link href="{% static 'plugins/animate-css/animate.css' %}" rel="stylesheet" />

    <!-- Ion Range -->
    <link href="{% static 'plugins/ion-rangeslider/css/ion.rangeSlider.css' %}" rel="stylesheet" />
    <link href="{% static 'plugins/ion-rangeslider/css/ion.rangeSlider.skinFlat.css' %}" rel="stylesheet" />

    <!-- Select Css -->
    <link href="{% static '/plugins/bootstrap-select/css/bootstrap-select.min.css' %}" rel="stylesheet" />

    <!-- JQuery DataTable Css -->
    <link href="{% static 'plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css' %}" rel="stylesheet">

    <!-- Custom Css -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

    <link href="{% static 'plugins/bootstrap-datepicker/css/bootstrap-datepicker.css' %}" rel="stylesheet">

    <!-- AdminBSB Themes. You can choose a theme from css/themes instead of get all themes -->
    <link href="{% static 'css/themes/all-themes.css' %}" rel="stylesheet" />
</head>

<body class="theme-red">
    <!-- Page Loader -->
    <div class="page-loader-wrapper">
        <div class="loader">
            <div class="preloader">
                <div class="spinner-layer pl-red">
                    <div class="circle-clipper left">
                        <div class="circle"></div>
                    </div>
                    <div class="circle-clipper right">
                        <div class="circle"></div>
                    </div>
                </div>
            </div>
            <p>Por favor aguarde...</p>
        </div>
    </div>
    <!-- #END# Page Loader -->
    <!-- Overlay For Sidebars -->
    <div class="overlay"></div>
    <!-- #END# Overlay For Sidebars -->
    <!-- Search Bar -->
    <!-- #END# Search Bar -->
    <!-- Top Bar -->
    <nav class="navbar">
        <div class="container-fluid">
            <div class="navbar-header">
                <a href="javascript:void(0);" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false"></a>
                <a href="javascript:void(0);" class="bars"></a>
                <a class="navbar-brand" href="{% url 'sistema:dashboard' %}">SGO - Gestão</a>
            </div>
        </div>
    </nav>
    <!-- #Top Bar -->
    <section>
        <!-- Left Sidebar -->
        <aside id="leftsidebar" class="sidebar">
            <!-- User Info -->
            <div class="user-info">
                <div class="image">
                    <img src="{% static 'images/user.png' %}" width="48" height="48" alt="User" />
                </div>
                <div class="info-container">
                    <div class="name" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ user.get_username }}</div>
                    <div class="email">{{ user.email }}</div>
                    <div class="btn-group user-helper-dropdown">
                        <i class="material-icons" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">keyboard_arrow_down</i>
                        <ul class="dropdown-menu pull-right">
                            <li><a href="{% url 'sistema:editarusuario' user.pk %}"><i class="material-icons">person</i>Perfil</a></li>
                            <li><a href="{% url 'sistema:logout' %}"><i class="material-icons">input</i>Sair</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- #User Info -->
            <!-- Menu -->
            <div class="menu">
                <ul class="list">
                    <li class="header">MENU PRINCIPAL</li>
                    <li class="active">
                        <a href="{% url 'sistema:dashboard' %}">
                            <i class="material-icons">home</i>
                            <span>Home</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'sistema:cadastrarempresa' %}">
                            <i class="material-icons">work</i>
                            <span>Empresa</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'sistema:listarchamados' %}">
                            <i class="material-icons">record_voice_over</i>
                            <span>Chamados</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'sistema:listarempreendimentos' %}">
                            <i class="material-icons">business</i>
                            <span>Emprendimentos</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'sistema:categoriasdeproblemas' %}">
                            <i class="material-icons">report_problem</i>
                            <span>Categorias de Problemas</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'sistema:listarusuarios' %}">
                            <i class="material-icons">people</i>
                            <span>Usuários</span>
                        </a>
                    </li>

                    <a href="javascript:void(0);" class="menu-toggle">
                        <i class="material-icons">archive</i>
                        <span>Relatórios</span>
                    </a>
                    <ul class="ml-menu">
                        <li>
                            <a href="{% url 'sistema:filtrochamado' %}">
                                <i class="material-icons">record_voice_over</i>
                                <span>Chamados</span>
                            </a>
                        </li>
                        <li>
                    </ul>
            </div>
            <!-- #Menu -->
            <!-- Footer -->
            <div class="legal">
                <div class="copyright">
                    &copy; Victor Fernandes, Marcelo Victor<br>Marcel Marques 2018, Renan Venâncio 2019.
                </div>

            </div>
            <!-- #Footer -->
        </aside>

    </section>
    <section class="content">
        {% block content %}
        <!-- O conteúdo da página vem aqui -->
        {% endblock%}
    </section>



    <!-- Jquery Core Js -->
    <script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>

    <!-- Bootstrap Core Js -->
    <script src="{% static 'plugins/bootstrap/js/bootstrap.js' %}"></script>

    <!-- Select Plugin Js -->
    <script src="{% static 'plugins/bootstrap-select/js/bootstrap-select.js' %}"></script>

    <!-- Slimscroll Plugin Js -->
    <script src="{% static 'plugins/jquery-slimscroll/jquery.slimscroll.js' %}"></script>

    <!-- Waves Effect Plugin Js -->
    <script src="{% static 'plugins/node-waves/waves.js' %}"></script>

    <!-- Jquery DataTable Plugin Js -->
    <script src="{% static 'plugins/jquery-datatable/jquery.dataTables.js' %}"></script>
    <script src="{% static 'plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js' %}"></script>
    <script src="{% static 'plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js' %}"></script>
    <script src="{% static 'plugins/jquery-datatable/extensions/export/buttons.flash.min.js' %}"></script>
    <script src="{% static 'plugins/jquery-datatable/extensions/export/jszip.min.js' %}"></script>
    <script src="{% static 'plugins/jquery-datatable/extensions/export/pdfmake.min.js' %}"></script>
    <script src="{% static 'plugins/jquery-datatable/extensions/export/vfs_fonts.js' %}"></script>
    <script src="{% static 'plugins/jquery-datatable/extensions/export/buttons.html5.min.js' %}"></script>
    <script src="{% static 'plugins/jquery-datatable/extensions/export/buttons.print.min.js' %}"></script>

    <!-- Jquery CountTo Plugin Js -->
    <script src="{% static 'plugins/jquery-countto/jquery.countTo.js' %}"></script>

    <!-- Custom Js -->
    <script src="{% static 'js/admin.js' %}"></script>

    <!-- Demo Js -->
    <script src="{% static 'js/demo.js' %}"></script>

    <script src="{% static 'js/pages/tables/jquery-datatable.js' %}"></script>

    <!-- Rate Plugin -->
    <script src="{% static 'plugins/rater-js/rater.js' %}"></script>


    <script src="{% static 'js/sb-admin-datatables.js' %}"></script>
   <!-- <script src="{% static 'js/pages/index.js' %}"></script> -->

    <script src="{% static 'js/pages/ui/modals.js' %}"></script>


    <script src="{% static 'js/pages/ui/range-sliders.js' %}"></script>

    <script src="{% static 'plugins/bootstrap-datepicker/js/bootstrap-datepicker.js' %}"></script>


    <script src="{% static 'plugins/ion-rangeslider/js/ion.rangeSlider.min.js' %}"></script>

    <!-- Sweet alert -->
    <script src="{% static 'plugins/sweetalert/sweetalert.min.js' %}"></script>

   <!-- Combos com buscas -->
    <script type="text/javascript">
        function msgDelete(redirecionar) {
            swal({
              title: "Deseja realmente deletar?",
              text: "Ao deletar esse registro o mesmo não pode ser recuperado posteriormente. Deseja prosseguir?",
              icon: "warning",
              buttons: true,
              buttons: ["Cancelar", "Sim"],
              dangerMode: true,
            })
            .then((willDelete) => {
              if (willDelete) {
                window.location = redirecionar;
              } else {
              }
            });
        }


         $.fn.datepicker.dates['en'] = {
            days: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
            daysShort: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
            daysMin: ["Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sáb"],
            months: ["Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"],
            monthsShort: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
            today: "Today",
            autoclose: true,
            disableTouchKeyboard: true,
            forceParse: true,
            format: "dd/mm/yyyy",
            titleFormat: "MM yyyy", /* Leverages same syntax as 'format' */
            weekStart: 0
         };

        $(document).ready(function(){
            $('select').selectpicker();
        });
    </script>


    <!-- Responsável por popular os selects dos chamados -->
    {% block scripts %}
      <script type="text/javascript">
        var cadastrar = false;
      </script>
    {% endblock %}
    <script src="{% static 'js/app.js' %}"></script>



    <style>
        .errorlist
        {
            color: red;
        }
    </style>



</body>

</html>

sistema/templates/sistema/login.html
{% load static %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="pt-br">

<html>
    <head>
        <meta charset="UTF-8">
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
        <title>SGO - Login</title>
        <!-- Favicon-->
        <link rel="icon" href="../../favicon.ico" type="image/x-icon">

        <!-- Google Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&amp;subset=latin,cyrillic-ext" rel="stylesheet" type="text/css">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">

        <!-- Bootstrap Core Css -->
        <link href="{% static 'plugins/bootstrap/css/bootstrap.css' %}" rel="stylesheet">

        <!-- Waves Effect Css -->
        <link href="{% static 'plugins/node-waves/waves.css' %}" rel="stylesheet">

        <!-- Animation Css -->
        <link href="{% static 'plugins/animate-css/animate.css' %}" rel="stylesheet">

        <!-- Custom Css -->
        <link href="{% static 'css/style.css' %}" rel="stylesheet">
    </head>

    <body class="login-page">
        <div class="login-box">
            <div class="logo">
                <a><b>SGO</b></a>
                <small>Sistema de Gerenciamento de Ocorrências</small>
            </div>
            <div class="card">
                <div class="body">
                    <form id="sign_in" method="POST" novalidate="novalidate">
                        {% csrf_token %}
                        <div class="msg">Digite suas credenciais para entrar</div>
                        <div class="input-group">
                            <span class="input-group-addon">
                                <i class="material-icons">person</i>
                            </span>
                            <div class="form-line">
                                {{ form.username|attr:'class: form-control'|attr:'placeholder: Usuario' }}
                            </div>
                        </div>
                        <div class="input-group">
                            <span class="input-group-addon">
                                <i class="material-icons">lock</i>
                            </span>
                            <div class="form-line">
                                {{ form.password|attr:'class: form-control'|attr:'placeholder: Senha' }}
                            </div>
                        </div>

                        {% if form.non_field_errors %}
                            <div class="alert alert-danger">
                              <strong>Por favor, entre com um usuário e senha corretos. Note que ambos os campos diferenciam maiúsculas e minúsculas.</strong>
                            </div>
                        {% endif %}

                        <button class="btn btn-block bg-red waves-effect" type="submit">Entrar</button>

                        <div class="row m-t-15 m-b--20">
                            <div class="col-xs-6">
                            </div>
                            <div class="col-xs-6 align-right">
                                <a href="/contas/password_reset/">Esqueceu a senha?</a>
                            </div>
                        </div>


                    </form>
                </div>
            </div>
        </div>

        <!-- Jquery Core Js -->
        <script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>

        <!-- Bootstrap Core Js -->
        <script src="{% static 'plugins/bootstrap/js/bootstrap.js' %}"></script>

        <!-- Waves Effect Plugin Js -->
        <script src="{% static 'plugins/node-waves/waves.js' %}"></script>

        <!-- Validation Plugin Js -->
        <script src="{% static 'plugins/jquery-validation/jquery.validate.js' %}"></script>

        <!-- Custom Js -->
        <script src="{% static 'js/admin.js' %}"></script>
        <script src="{% static 'js/pages/examples/sign-in.js' %}"></script>


    </body>
</html>