engenharia/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from rest_framework.documentation import include_docs_urls
from django.contrib.auth import urls



urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/docs/', include_docs_urls(title='SGO - Documentação da API', public=False)),
    path('', include('sistema.urls', namespace='sistema')),
    path('contas/', include('django.contrib.auth.urls')),

]

if settings.DEBUG is True:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


sistema/api/urls.py
from django.urls import path, include
from rest_framework import routers

from sistema.api import viewset
from rest_framework.authtoken.views import obtain_auth_token
#Swagger



router = routers.DefaultRouter()


router.register(r'usuario', viewset.UsuarioViewApi, base_name='Usuarios')
router.register(r'empresa', viewset.EmpresaListViewAPI, base_name='Empresa')
router.register(r'listarempreendimentos', viewset.EmpreendimentoListViewAPI, base_name='Empreendimento')
router.register(r'listarblocos', viewset.BlocoListViewAPI, base_name='Bloco')
router.register(r'listarapartamentos', viewset.ApartamentoListViewAPI, base_name='Apartamento')
router.register(r'listageralapartamentos', viewset.ApartamentoListaGeral, base_name='Apartamento')
router.register(r'listarcategoriasdeproblema', viewset.CategoriaDeProblemaListViewAPI, base_name='CategoriaDeProblema')
router.register(r'listarareascomuns', viewset.AreaComumListViewAPI, base_name='AreaComum')
router.register(r'imagem', viewset.ImagemUploadViewAPI, base_name='ImagemUpload')
router.register(r'chamado', viewset.ChamadoCreateViewAPI, base_name='Chamado')
router.register(r'listarchamados', viewset.ChamadoListViewAPI, base_name='Chamado')

urlpatterns = [

    path('api/', include(router.urls)),
    path('obter-token/', obtain_auth_token, name='api_token_auth'),


]

sistema/urls.py
# coding=utf-8


from django.urls import path, include
from . import views
from rest_framework.urlpatterns import format_suffix_patterns
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required  #Staff
from django.urls import reverse_lazy
from sistema.api import viewset

app_name = 'sistema'






urlpatterns = [
    path('', include('sistema.api.urls')),

    path('', staff_member_required(views.DashboardView.as_view(), login_url=reverse_lazy('sistema:login')), name='dashboard'),

    #Login e logout
    path('login/', auth_views.login, {'template_name': 'sistema/login.html'}, name='login'),
    path('logout/', auth_views.logout, {'next_page': reverse_lazy('sistema:dashboard')}, name='logout'),


    path('empresa/cadastrarempresa/', staff_member_required(
        views.EmpresaCreateView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='cadastrarempresa'),

    path('empresa/editarempresa/<int:pk>/', staff_member_required(
        views.EmpresaEditView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='editarempresa'),

    path('empresa/deletarempresa/<int:pk>/', staff_member_required(
        views.EmpresaDeleteView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='deletarempresa'),

    path('usuarios/editarusuario/<int:pk>/mudarsenha', staff_member_required(
        views.UsuariosPasswordUpdateView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='mudarsenhausuario'),

    path('usuarios/cadastrarusuario/', staff_member_required(
        views.UsuariosCreateView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='cadastrarusuario'),

    path('usuarios/listarusuarios/', staff_member_required(
        views.UsuariosListView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='listarusuarios'),

    path('usuarios/editarusuario/<int:pk>/', staff_member_required(
        views.UsuariosUpdateView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='editarusuario'),

    path('usuarios/deletarusuario/<int:pk>/', staff_member_required(
        views.UsuariosDeleteView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='deletarusuario'),



    path('empreendimentos/listarempreendimentos/', staff_member_required(
        views.EmpreendimentoListView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='listarempreendimentos'),
    path('empreendimentos/cadastrarempreendimento/', staff_member_required(
        views.EmpreendimentoCreateView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='cadastrarempreendimento'),
    path('empreendimentos/editarempreendimento/<int:pk>/', staff_member_required(
        views.EmpreendimentoUpdateView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='editarempreendimento'),
    path('empreendimentos/deletarempreendimento/<int:pk>/', staff_member_required(
        views.EmpreendimentoDeleteView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='deletarempreendimento'),


    path('empreendimentos/areascomuns/', staff_member_required(
        views.AreasComunsListView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='listarareascomuns'),
    path('empreendimentos/areascomuns/cadastrarareacomum', staff_member_required(
        views.AreaComumCreateView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='cadastrarareacomum'),
    path('empreendimentos/areascomuns/editarareacomum/<int:pk>/', staff_member_required(
        views.AreaComumUpdateView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='editarareacomum'),
    path('empreendimentos/areascomuns/deletarareacomum/<int:pk>/', staff_member_required(
        views.AreaComumDeleteView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='deletarareacomum'),


    path('empreendimentos/blocos/listarblocos/', staff_member_required(
        views.BlocoListView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='listarblocos'),
    path('empreendimentos/blocos/cadastrarbloco/', staff_member_required(
        views.BlocoCreateView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='cadastrarbloco'),
    path('empreendimentos/blocos/editarbloco/<int:pk>/', staff_member_required(
        views.BlocoUpdateView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='editarbloco'),
    path('empreendimentos/blocos/deletarbloco/<int:pk>/', staff_member_required(
        views.BlocoDeleteView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='deletarbloco'),


    path('empreendimentos/blocos/listarapartamentos/', staff_member_required(
        views.ApartamentoListView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='listarapartamentos'),
    path('empreendimentos/blocos/cadastrarapartamento/', staff_member_required(
        views.ApartamentoCreateView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='cadastrarapartamento'),
    path('empreendimentos/blocos/editarapartamento/<int:pk>/', staff_member_required(
        views.ApartamentoUpdateView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='editarapartamento'),
    path('empreendimentos/blocos/deletarapartamento/<int:pk>/', staff_member_required(
        views.ApartamentoDeleteView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='deletarapartamento'),
    path('json/apartamentos/proprietario/<int:pk>', staff_member_required(
         views.ApartamentoProprietarioListJson.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='apartamentoproprietario'),


    path('problemas/listarcategorias/', staff_member_required(
        views.CategoriaDeProblemaListView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='categoriasdeproblemas'),
    path('problemas/cadastrarcategoria/', staff_member_required(
        views.CategoriaDeProblemaCreateView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='cadastrarcategoriadeproblema'),
    path('problemas/editarcategoria/<int:pk>/', staff_member_required(
        views.CategoriaDeProblemaUpdateView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='editarcategoriadeproblema'),
    path('problemas/deletarcategoria/<int:pk>/', staff_member_required(
        views.CategoriaDeProblemaDeleteView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='deletarcategoriadeproblema'),


    path('chamados/listarchamados/', staff_member_required(
        views.ChamadoListView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='listarchamados'),
    path('chamados/cadastrarchamado/', staff_member_required(
        views.ChamadoCreateView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='cadastrarchamado'),
    path('chamados/editarchamado/<int:pk>/', staff_member_required(
        views.ChamadoUpdateView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='editarchamado'),
    path('chamados/deletarchamado/<int:pk>/', staff_member_required(
        views.ChamadoDeleteView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='deletarchamado'),

    path('chamados/imprimir/<int:pk>/', staff_member_required(
        views.ChamadoPrintView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='imprimirchamado'),


    path('chamados/deletarevento/<int:pk>/', staff_member_required(
        views.EventoChamadoDeleteView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='deletareventochamado'),


    path('filtro/chamado/', staff_member_required(
        views.RelatorioChamadoFiltro.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='filtrochamado'),



]

sistema/forms.py
# coding=utf-8
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm
from django import forms
from .models import *
from django.core.exceptions import ValidationError
class EmpresaForm(forms.ModelForm):
    class Meta:
        model = Empresa
        fields = '__all__'


class UsuarioForm(UserCreationForm):
    class Meta:
        model = Usuarios
        #fields = '__all__'
        exclude = ['password', 'last_login', 'is_active', 'date_joined']


class UsuarioEditForm(forms.ModelForm):
    class Meta:
        model = Usuarios
        exclude = ['password', 'last_login', 'is_active', 'date_joined', 'apartamentos']


class UsuarioPasswordChangeForm(UserCreationForm):
    class Meta:
        model = Usuarios
        fields = ['password1', 'password2']


class EmpreendimentoForm(forms.ModelForm):
    class Meta:
        model = Empreendimento
        fields = ['nomeEmpreendimento']


class AreaComumForm(forms.ModelForm):
    class Meta:
        model = AreaComum
        fields = ['nomeArea', ]


class BlocoForm(forms.ModelForm):
    class Meta:
        model = Bloco
        fields = ['empreendimento', 'bloco']


class ApartamentoForm(forms.ModelForm):
    class Meta:
        model = Apartamento
        fields = ['bloco', 'apartamento', 'proprietario', 'inicioGarantia']

    def clean_inicioGarantia(self):
        cleaned_data = super(ApartamentoForm, self).clean()
        inicioGarantia = cleaned_data.get("inicioGarantia")
        proprietario = cleaned_data.get("proprietario")

        if(inicioGarantia == None) and (not (proprietario == None)):
            raise ValidationError("Selecione a data de início da garantia do apartamento.")
        return inicioGarantia

class CategoriaDeProblemaForm(forms.ModelForm):
    class Meta:
        model = CategoriaDeProblema
        fields = ['nomeCategoria']


class ChamadoForm(forms.ModelForm):
    class Meta:
        model = Chamado
        fields = '__all__'
        exclude = ['protocolo', 'novosEventos']



class EventoChamadoForm(forms.ModelForm):
    class Meta:
        model = EventosChamado
        fields = ['descricaoEvento']
        #exclude = ['protocolo']













sistema/templates/sistema/usuarios/editarusuario.html
{% extends 'sistema/base.html' %}

{% load widget_tweaks %}

{% block title %}Editar usuário | {{ block.super }}{% endblock %}

{% block content %}
<div class="container-fluid">

    <div class="block-header">
        <ol class="breadcrumb">
            <li>
                <a href="{% url 'sistema:listarusuarios' %}">
                    <i class="material-icons">people</i> Usuários
                </a>
            </li>
            <li class="active">
                <i class="material-icons">edit</i> Editar Usuário
            </li>
        </ol>
    </div>
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                EDITAR USUÁRIO
                            </h2>
                        </div>
                        <div class="body">
                            <!-- Nav tabs -->
                            <ul class="nav nav-tabs tab-nav-right" role="tablist">
                                <li role="presentation" class="active"><a href="#dados" data-toggle="tab" aria-expanded="true">PERFIL</a></li>
                                <li role="presentation" class=""><a href="#apartamentos" data-toggle="tab" aria-expanded="false">APARTAMENTOS</a></li>

                            </ul>

                            <!-- Tab panes -->
                            <div class="tab-content">
                                <div role="tabpanel" class="tab-pane fade active in" id="dados">
                                    <form method="POST">
                                        {% csrf_token %}

                                        <div class="row clearfix">
                                            <div class="col-sm-6">
                                                <label for="{{ form.first_name.auto_id }}">{{ form.first_name.label }} *</label>
                                                <div class="form-group">
                                                    <div class="form-line">
                                                        {{ form.first_name|add_class:"form-control"}}
                                                        {{ form.first_name.errors }}
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="col-sm-6">
                                                <label for="{{ form.last_name.auto_id }}">{{ form.last_name.label }}</label>
                                                <div class="form-group">
                                                    <div class="form-line">
                                                        {{ form.last_name|add_class:"form-control"}}
                                                        {{ form.last_name.errors }}
                                                    </div>
                                                </div>
                                            </div>
                                        </div>


                                        <div class="row clearfix">
                                            <div class="col-sm-12">
                                                <label for="{{ form.cpf.auto_id }}">{{ form.cpf.label }} *</label>
                                                <div class="form-group">
                                                    <div class="form-line">
                                                        {{ form.cpf|add_class:"form-control"}}
                                                    </div>
                                                    {{ form.cpf.errors }}
                                                </div>
                                            </div>
                                        </div>

                                        <div class="row clearfix">
                                            <div class="col-sm-12">
                                                <label for="{{ form.email.auto_id }}">{{ form.email.label }} *</label>
                                                <div class="form-group">
                                                    <div class="form-line">
                                                        {{ form.email|add_class:"form-control"}}
                                                    </div>
                                                    {{ form.email.errors }}
                                                </div>
                                            </div>
                                        </div>

                                        <div class="row clearfix">
                                            <div class="col-sm-6">
                                                <label for="{{ form.telefone1.auto_id }}">{{ form.telefone1.label }}</label>
                                                <div class="form-group">
                                                    <div class="form-line">
                                                        {{ form.telefone1|add_class:"form-control"}}
                                                        {{ form.telefone1.errors }}
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="col-sm-6">
                                                <label for="{{ form.telefone2.auto_id }}">{{ form.telefone2.label }}</label>
                                                <div class="form-group">
                                                    <div class="form-line">
                                                        {{ form.telefone2|add_class:"form-control"}}
                                                        {{ form.telefone2.errors }}
                                                    </div>
                                                </div>
                                            </div>
                                        </div>


                                        <div class="row clearfix">
                                            <div class="col-sm-12">
                                                <label for="{{ form.username.auto_id }}">{{ form.username.label }} *</label>
                                                <div class="form-group">
                                                    <div class="form-line">
                                                        {{ form.username|add_class:"form-control"}}
                                                    </div>
                                                    {{ form.username.errors }}
                                                </div>
                                            </div>
                                        </div>


                                        <div class="row clearfix">
                                            <div class="col-sm-12">
                                                <label for="{{ form.limiteChamadosDia.auto_id }}">{{ form.limiteChamadosDia.label }} *</label>
                                                <div class="form-group">
                                                    <div class="form-line">
                                                        {{ form.limiteChamadosDia|add_class:"form-control"}}
                                                    </div>
                                                    {{ form.limiteChamadosDia.errors }}
                                                </div>
                                            </div>
                                        </div>

                                        <hr>
                                        <h6 class="font-bold col-pink">Se a caixa abaixo estiver ligada, o usuário terá
                                            acesso ao adminstrativo.</h6>
                                        <div class="demo-switch-title">Usuário membro da equipe</div>
                                        <div class="switch">
                                            <label>{{ form.is_staff|add_class:"form-check-label"}}<span
                                                    class="lever switch-col-red"></span></label>
                                        </div>
                                        <hr>


                                        <div class="form-row">
                                            <div class="form-group col-md-12"><br>
                                                Para mudar a senha <a
                                                        href="/usuarios/editarusuario/{{ usuarios.id }}/mudarsenha">clique
                                                    aqui</a>
                                            </div>
                                        </div>

                                        <br>

                                        <button type="submit" class="btn btn-primary m-t-15 waves-effect"><i
                                                class="material-icons">save</i><span>SALVAR</span></button>

                                        <a class="btn btn-danger m-t-15 waves-effect" style="background-color: red; border-color: red;" onclick=msgDelete("{% url 'sistema:deletarusuario' usuarios.pk %}") >
                                            <i class="material-icons">delete</i>
                                            <span>DELETAR</span>
                                        </a>

                                    </form>
                                </div>
                                <div role="tabpanel" class="tab-pane fade" id="apartamentos">
                                    <table class="table table-bordered">
                                        <thead>
                                            <tr>
                                                <td><b>EMPREENDIMENTO</b></td>
                                                <td><b>BLOCO</b></td>
                                                <td><b>APARTAMENTO</b></td>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for apartamento in view.apartamentos %}
                                                <tr>
                                                    <td><a href="{{ apartamento.bloco.empreendimento.get_absolute_url }}">{{ apartamento.bloco.empreendimento }}</a></td>
                                                    <td><a href="{{ apartamento.bloco.get_absolute_url }}">{{ apartamento.bloco.bloco }}</a></td>
                                                    <td><a href="{{ apartamento.get_absolute_url }}">{{ apartamento.apartamento }}</a></td>
                                                </tr>
                                            {% endfor %}

                                        </tbody>
                                    </table>

                                </div>

                            </div>
                        </div>
                    </div>
                </div>
        </div>

</div>
{% endblock %}

sistema/templates/sistema/usuarios/listarusuarios.html
{% extends 'sistema/base.html' %}

{% block title %}Usuários | {{ block.super }}{% endblock %}

{% block content %}


<div class="container-fluid">

    <div class="block-header">
            <ol class="breadcrumb">

                <li class="active">
                    <i class="material-icons">people</i> Usuários
                </li>
            </ol>
    </div>

    <!-- Exportable Table -->
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>

                        <a class="btn bg-blue" href="{% url 'sistema:cadastrarusuario' %}" >
                            <i class="material-icons">add</i>
                            <span>Novo</span>
                        </a>


                    </h2>

                </div>
                <div class="body">
                    <div class="table-responsive">
                        <table class="table table-bordered table-striped table-hover dataTable js-exportable">
                            <thead>
                                <tr>
                                    <th>Nome</th>
                                    <th>CPF</th>
                                    <th>E-mail</th>
                                    <th>Login</th>
                                    <th>Membro da equipe</th>
                                </tr>
                            </thead>
                            <tfoot>
                                <tr>
                                    <th>Nome</th>
                                    <th>E-mail</th>
                                    <th>Login</th>
                                    <th>Membro da equipe</th>
                                </tr>
                            </tfoot>
                            <tbody>

                            {% for usuario in usuarios %}
                            <tr>
                                <td>{{ usuario.first_name }}</td>
                                <td>{{ usuario.cpf }}</td>
                                <td><a href="/usuarios/editarusuario/{{ usuario.id }}">{{ usuario.email }}</a></td>
                                <td><a href="/usuarios/editarusuario/{{ usuario.id }}">{{ usuario.username }}</a></td>

                                <td>

                                    {% if usuario.is_staff %}
                                        <span class="new badge bg-green">Sim</span>
                                    {% else %}
                                        <span class="new badge bg-red">Não</span>

                                    {% endif %}
                                </td>

                            </tr>
                            {% endfor %}

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- #END# Exportable Table -->
</div>
{% endblock %}



sistema/templates/sistema/usuarios/mudarsenha.html
{% extends 'sistema/base.html' %}



{% block title %}Mudar senha | {{ block.super }}{% endblock %}

{% block content %}
{% load widget_tweaks %}


<div class="container-fluid">

        <div class="block-header">
            <ol class="breadcrumb">
                <li>
                    <a href="{% url 'sistema:listarusuarios' %}">
                        <i class="material-icons">people</i> Usuários
                    </a>
                </li>
                <li>
                    <a href="/usuarios/editarusuario/{{ usuarios.id }}">
                        <i class="material-icons">edit</i> Editar Usuário
                    </a>
                </li>
                <li class="active">
                    <i class="material-icons">lock</i> Mudar senha
                </li>
            </ol>
        </div>

        <!-- Vertical Layout -->
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                        <h2 class="text-uppercase">
                            MUDAR SENHA DE {{ usuarios.first_name}}
                        </h2>
                    </div>
                    <div class="body">

                        <form method="POST">
                        {% csrf_token %}

                            <label for="{{ form.password1.auto_id }}">{{ form.password1.label }}</label>
                            <div class="form-group">
                                <div class="form-line">
                                {{ form.password1|add_class:"form-control"}}
                                </div>
                               {{ form.password1.errors }}
                            </div>

                           <blockquote class="m-b-25">
                              <h6 class="font-italic col-pink">
                                 Sua senha não pode ser tão parecida com suas outras informações pessoais.<br>
                                 Sua senha precisa conter pelo menos 8 caracteres.<br>
                                 Sua senha não pode ser uma senha habitualmente utilizada.<br>
                                 Sua senha não pode ser inteiramente numérica.<br>
                              </h6>

                            </blockquote>


                            <label for="{{ form.password2.auto_id }}">{{ form.password2.label }}</label>
                            <div class="form-group">
                                <div class="form-line">
                                {{ form.password2|add_class:"form-control"}}
                                </div>
                               {{ form.password2.errors }}
                            </div>


                            <br>
                            <button type="submit" class="btn btn-primary m-t-15 waves-effect">SALVAR</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
</div>

{% endblock %}