engenharia/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from rest_framework.documentation import include_docs_urls
from django.contrib.auth import urls



urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/docs/', include_docs_urls(title='SGO - Documentação da API', public=False)),
    path('', include('sistema.urls', namespace='sistema')),
    path('contas/', include('django.contrib.auth.urls')),

]

if settings.DEBUG is True:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


sistema/api/urls.py
from django.urls import path, include
from rest_framework import routers

from sistema.api import viewset
from rest_framework.authtoken.views import obtain_auth_token
#Swagger



router = routers.DefaultRouter()


router.register(r'usuario', viewset.UsuarioViewApi, base_name='Usuarios')
router.register(r'empresa', viewset.EmpresaListViewAPI, base_name='Empresa')
router.register(r'listarempreendimentos', viewset.EmpreendimentoListViewAPI, base_name='Empreendimento')
router.register(r'listarblocos', viewset.BlocoListViewAPI, base_name='Bloco')
router.register(r'listarapartamentos', viewset.ApartamentoListViewAPI, base_name='Apartamento')
router.register(r'listageralapartamentos', viewset.ApartamentoListaGeral, base_name='Apartamento')
router.register(r'listarcategoriasdeproblema', viewset.CategoriaDeProblemaListViewAPI, base_name='CategoriaDeProblema')
router.register(r'listarareascomuns', viewset.AreaComumListViewAPI, base_name='AreaComum')
router.register(r'imagem', viewset.ImagemUploadViewAPI, base_name='ImagemUpload')
router.register(r'chamado', viewset.ChamadoCreateViewAPI, base_name='Chamado')
router.register(r'listarchamados', viewset.ChamadoListViewAPI, base_name='Chamado')

urlpatterns = [

    path('api/', include(router.urls)),
    path('obter-token/', obtain_auth_token, name='api_token_auth'),


]

sistema/urls.py
# coding=utf-8


from django.urls import path, include
from . import views
from rest_framework.urlpatterns import format_suffix_patterns
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required  #Staff
from django.urls import reverse_lazy
from sistema.api import viewset

app_name = 'sistema'






urlpatterns = [
    path('', include('sistema.api.urls')),

    path('', staff_member_required(views.DashboardView.as_view(), login_url=reverse_lazy('sistema:login')), name='dashboard'),

    #Login e logout
    path('login/', auth_views.login, {'template_name': 'sistema/login.html'}, name='login'),
    path('logout/', auth_views.logout, {'next_page': reverse_lazy('sistema:dashboard')}, name='logout'),


    path('empresa/cadastrarempresa/', staff_member_required(
        views.EmpresaCreateView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='cadastrarempresa'),

    path('empresa/editarempresa/<int:pk>/', staff_member_required(
        views.EmpresaEditView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='editarempresa'),

    path('empresa/deletarempresa/<int:pk>/', staff_member_required(
        views.EmpresaDeleteView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='deletarempresa'),

    path('usuarios/editarusuario/<int:pk>/mudarsenha', staff_member_required(
        views.UsuariosPasswordUpdateView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='mudarsenhausuario'),

    path('usuarios/cadastrarusuario/', staff_member_required(
        views.UsuariosCreateView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='cadastrarusuario'),

    path('usuarios/listarusuarios/', staff_member_required(
        views.UsuariosListView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='listarusuarios'),

    path('usuarios/editarusuario/<int:pk>/', staff_member_required(
        views.UsuariosUpdateView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='editarusuario'),

    path('usuarios/deletarusuario/<int:pk>/', staff_member_required(
        views.UsuariosDeleteView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='deletarusuario'),



    path('empreendimentos/listarempreendimentos/', staff_member_required(
        views.EmpreendimentoListView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='listarempreendimentos'),
    path('empreendimentos/cadastrarempreendimento/', staff_member_required(
        views.EmpreendimentoCreateView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='cadastrarempreendimento'),
    path('empreendimentos/editarempreendimento/<int:pk>/', staff_member_required(
        views.EmpreendimentoUpdateView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='editarempreendimento'),
    path('empreendimentos/deletarempreendimento/<int:pk>/', staff_member_required(
        views.EmpreendimentoDeleteView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='deletarempreendimento'),


    path('empreendimentos/areascomuns/', staff_member_required(
        views.AreasComunsListView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='listarareascomuns'),
    path('empreendimentos/areascomuns/cadastrarareacomum', staff_member_required(
        views.AreaComumCreateView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='cadastrarareacomum'),
    path('empreendimentos/areascomuns/editarareacomum/<int:pk>/', staff_member_required(
        views.AreaComumUpdateView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='editarareacomum'),
    path('empreendimentos/areascomuns/deletarareacomum/<int:pk>/', staff_member_required(
        views.AreaComumDeleteView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='deletarareacomum'),


    path('empreendimentos/blocos/listarblocos/', staff_member_required(
        views.BlocoListView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='listarblocos'),
    path('empreendimentos/blocos/cadastrarbloco/', staff_member_required(
        views.BlocoCreateView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='cadastrarbloco'),
    path('empreendimentos/blocos/editarbloco/<int:pk>/', staff_member_required(
        views.BlocoUpdateView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='editarbloco'),
    path('empreendimentos/blocos/deletarbloco/<int:pk>/', staff_member_required(
        views.BlocoDeleteView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='deletarbloco'),


    path('empreendimentos/blocos/listarapartamentos/', staff_member_required(
        views.ApartamentoListView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='listarapartamentos'),
    path('empreendimentos/blocos/cadastrarapartamento/', staff_member_required(
        views.ApartamentoCreateView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='cadastrarapartamento'),
    path('empreendimentos/blocos/editarapartamento/<int:pk>/', staff_member_required(
        views.ApartamentoUpdateView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='editarapartamento'),
    path('empreendimentos/blocos/deletarapartamento/<int:pk>/', staff_member_required(
        views.ApartamentoDeleteView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='deletarapartamento'),
    path('json/apartamentos/proprietario/<int:pk>', staff_member_required(
         views.ApartamentoProprietarioListJson.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='apartamentoproprietario'),


    path('problemas/listarcategorias/', staff_member_required(
        views.CategoriaDeProblemaListView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='categoriasdeproblemas'),
    path('problemas/cadastrarcategoria/', staff_member_required(
        views.CategoriaDeProblemaCreateView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='cadastrarcategoriadeproblema'),
    path('problemas/editarcategoria/<int:pk>/', staff_member_required(
        views.CategoriaDeProblemaUpdateView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='editarcategoriadeproblema'),
    path('problemas/deletarcategoria/<int:pk>/', staff_member_required(
        views.CategoriaDeProblemaDeleteView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='deletarcategoriadeproblema'),


    path('chamados/listarchamados/', staff_member_required(
        views.ChamadoListView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='listarchamados'),
    path('chamados/cadastrarchamado/', staff_member_required(
        views.ChamadoCreateView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='cadastrarchamado'),
    path('chamados/editarchamado/<int:pk>/', staff_member_required(
        views.ChamadoUpdateView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='editarchamado'),
    path('chamados/deletarchamado/<int:pk>/', staff_member_required(
        views.ChamadoDeleteView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='deletarchamado'),

    path('chamados/imprimir/<int:pk>/', staff_member_required(
        views.ChamadoPrintView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='imprimirchamado'),


    path('chamados/deletarevento/<int:pk>/', staff_member_required(
        views.EventoChamadoDeleteView.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='deletareventochamado'),


    path('filtro/chamado/', staff_member_required(
        views.RelatorioChamadoFiltro.as_view(), login_url=reverse_lazy('sistema:login')
    ), name='filtrochamado'),



]

sistema/forms.py
# coding=utf-8
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm
from django import forms
from .models import *
from django.core.exceptions import ValidationError
class EmpresaForm(forms.ModelForm):
    class Meta:
        model = Empresa
        fields = '__all__'


class UsuarioForm(UserCreationForm):
    class Meta:
        model = Usuarios
        #fields = '__all__'
        exclude = ['password', 'last_login', 'is_active', 'date_joined']


class UsuarioEditForm(forms.ModelForm):
    class Meta:
        model = Usuarios
        exclude = ['password', 'last_login', 'is_active', 'date_joined', 'apartamentos']


class UsuarioPasswordChangeForm(UserCreationForm):
    class Meta:
        model = Usuarios
        fields = ['password1', 'password2']


class EmpreendimentoForm(forms.ModelForm):
    class Meta:
        model = Empreendimento
        fields = ['nomeEmpreendimento']


class AreaComumForm(forms.ModelForm):
    class Meta:
        model = AreaComum
        fields = ['nomeArea', ]


class BlocoForm(forms.ModelForm):
    class Meta:
        model = Bloco
        fields = ['empreendimento', 'bloco']


class ApartamentoForm(forms.ModelForm):
    class Meta:
        model = Apartamento
        fields = ['bloco', 'apartamento', 'proprietario', 'inicioGarantia']

    def clean_inicioGarantia(self):
        cleaned_data = super(ApartamentoForm, self).clean()
        inicioGarantia = cleaned_data.get("inicioGarantia")
        proprietario = cleaned_data.get("proprietario")

        if(inicioGarantia == None) and (not (proprietario == None)):
            raise ValidationError("Selecione a data de início da garantia do apartamento.")
        return inicioGarantia

class CategoriaDeProblemaForm(forms.ModelForm):
    class Meta:
        model = CategoriaDeProblema
        fields = ['nomeCategoria']


class ChamadoForm(forms.ModelForm):
    class Meta:
        model = Chamado
        fields = '__all__'
        exclude = ['protocolo', 'novosEventos']



class EventoChamadoForm(forms.ModelForm):
    class Meta:
        model = EventosChamado
        fields = ['descricaoEvento']
        #exclude = ['protocolo']













sistema/templates/sistema/problemas/cadastrodecategoria.html
{% extends 'sistema/base.html' %}

{% load widget_tweaks %}

{% block title %}Cadastrar categoria de problema | {{ block.super }}{% endblock %}

{% block content %}
<div class="container-fluid">

    <div class="block-header">
        <ol class="breadcrumb">
            <li>
                <a href="{% url 'sistema:categoriasdeproblemas' %}">
                    <i class="material-icons">report_problem</i> Categorias dos Problemas
                </a>
            </li>

            <li class="active">
                <i class="material-icons">add</i> Nova Categoria
            </li>
        </ol>
    </div>

    <!-- Vertical Layout -->
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        CADASTRAR CATEGORIA
                    </h2>
                </div>
                <div class="body">

                    <form method="POST">
                        {% csrf_token %}

                        <label for="{{ form.nomeCategoria.auto_id }}">{{ form.nomeCategoria.label }}</label>
                        <div class="form-group">
                            <div class="form-line">
                                {{ form.nomeCategoria|add_class:"form-control"}}
                            </div>
                            {{ form.nomeCategoria.errors }}
                        </div>
                        <br>
                        <button type="submit" class="btn btn-primary m-t-15 waves-effect">SALVAR</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

sistema/templates/sistema/problemas/editarcategoria.html
{% extends 'sistema/base.html' %}

{% load widget_tweaks %}

{% block title %}{% endblock %}

{% block content %}
<div class="container-fluid">

    <div class="block-header">
        <ol class="breadcrumb">
            <li>
                <a href="{% url 'sistema:categoriasdeproblemas' %}">
                    <i class="material-icons">report_problem</i> Categorias dos Problemas
                </a>
            </li>

            <li class="active">
                <i class="material-icons">add</i> Nova Categoria
            </li>
        </ol>
    </div>

    <!-- Vertical Layout -->
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        EDITAR CATEGORIA
                    </h2>
                </div>
                <div class="body">

                    <form method="POST">
                        {% csrf_token %}

                        <label for="{{ form.nomeCategoria.auto_id }}">{{ form.nomeCategoria.label }}</label>
                        <div class="form-group">
                            <div class="form-line">
                                {{ form.nomeCategoria|add_class:"form-control"}}
                            </div>
                            {{ form.nomeCategoria.errors }}
                        </div>
                        <br>
                        <button type="submit" class="btn btn-primary m-t-15 waves-effect"><i class="material-icons">save</i><span>SALVAR</span></button>

                        <a class="btn btn-danger m-t-15 waves-effect" style="background-color: red; border-color: red;" onclick=msgDelete("{% url 'sistema:deletarcategoriadeproblema' categoria.pk %}") >
                            <i class="material-icons">delete</i>
                            <span>DELETAR</span>
                        </a>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

sistema/templates/sistema/problemas/listarcategorias.html
{% extends 'sistema/base.html' %}

{% block title %}Categorias de problemas | {{ block.super }}{% endblock %}

{% block content %}
<div class="container-fluid">

    <div class="block-header">
            <ol class="breadcrumb">

                <li class="active">
                    <i class="material-icons">report_problem</i> Categorias dos Problemas
                </li>
            </ol>
    </div>

    <!-- Exportable Table -->
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>

                        <a class="btn bg-blue" href="{% url 'sistema:cadastrarcategoriadeproblema' %}" >
                            <i class="material-icons">add</i>
                            <span>Nova Categoria</span>
                        </a>
                    </h2>
                </div>
                <div class="body">
                    <div class="table-responsive">
                        <table class="table table-bordered table-striped table-hover dataTable js-exportable">
                          <thead>
                            <tr>
                              <th>Data de cadastro</th>
                              <th>Categoria</th>
                            </tr>
                          </thead>
                          <tfoot>
                            <tr>
                              <th>Data de cadastro</th>
                              <th>Categoria</th>
                            </tr>
                          </tfoot>
                          <tbody>
                            {% for categoria in categorias %}
                                <tr>
                                    <td>{{ categoria.dataCadastro }}</td>
                                    <td><a href="{{ categoria.get_absolute_url }}">{{ categoria.nomeCategoria }}</a></td>
                                </tr>
                            {% endfor %}
                          </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}



